### ISSUE TITLE
Is there some way to get all the Capital IQ IDs using this library?

### ISSUE THREAD

**Issue by amirsani** [faaez/capiq-python#1]
Sorry for the non-issue post, but I need to scrape all the Capital IQ IDs into a csv and didn't see this functionality.

Cheers,

Amir

**Comment by faaez** [comment]
@amirsani unfortunately that functionality is not available currently. Do you know if CapIQ's own API supports that query?

**Comment by amirsani** [comment]
Hi Faaez,

They don't have this implemented, so I wrote a scraper to get them. It
takes forever though.

Best,

Amir

www.amirsani.com
Postdoctoral Researcher
Centre d'économie de la Sorbonne CNRS
Paris School of Economics
