### ISSUE TITLE
CapIQClient method names are too obscure

### ISSUE THREAD

**Issue by airstrike** [faaez/capiq-python#2]
First of all, thanks for writing this package. I'm sure it will be very useful for my needs.

As I went through the source code for the first time, I noticed that the `CapIQClient` methods in the main `capiq.py` module have very obscure nmaes, i.e. `gdsp`, `gdspv`, `gdst`, `gdshe`, `gdshv`, `gdsg`. Readability counts, and the current names make it impossible to tell what each method does without reading through the code.

**Comment by faaez** [comment]
Thanks for the comment!

I intended for this to be a very thin wrapper and as such, the function
names all correspond exactly to CapIQ's own API. Would be glad to make
changes if you have suggestions!

**Comment by airstrike** [comment]
Thanks for the quick reply! I guess what I'm missing here  then is a reference guide to CapIQ's API. I've googled around but can't find anything. Do you know where it is available?

**Comment by faaez** [comment]
@airstrike CapIQ API documentation isn't publicly available, to my knowledge. Please get in touch with Capital IQ support for specific function/mnemonic details and pricing information.

**Comment by kirkportas** [comment]
The full Mnemonic list is here. You'll need a CapIQ login to access it.
http://support.standardandpoors.com/gds/images/stories/Excel_Plug-in/SDK/combined_data_items_final.xlsx
